#!/bin/sh
# Package the CatalinaPerformance local GUI as a development-only .app bundle.

set -u

SCRIPT_DIR=$(CDPATH= cd "$(dirname "$0")" && pwd -P) || exit 1
REPO_ROOT=$(CDPATH= cd "$SCRIPT_DIR/.." && pwd -P) || exit 1
PACKAGE_DIR="$REPO_ROOT/app/CatalinaPerformance"
APP_BUILD_DIR="$REPO_ROOT/build"
APP_NAME="CatalinaPerformance"
APP_BUNDLE="$APP_BUILD_DIR/$APP_NAME.app"
CONTENTS_DIR="$APP_BUNDLE/Contents"
MACOS_DIR="$CONTENTS_DIR/MacOS"
BUNDLE_EXECUTABLE="$MACOS_DIR/$APP_NAME"
GUI_EXECUTABLE="$MACOS_DIR/${APP_NAME}-gui"
INFO_PLIST="$CONTENTS_DIR/Info.plist"

error() {
    printf 'Error: %s\n' "$1" >&2
}

require_file() {
    if [ ! -f "$1" ]; then
        error "Required file was not found: $1"
        exit 1
    fi
}

require_executable_or_file() {
    if [ ! -f "$1" ]; then
        error "Required script was not found: $1"
        exit 1
    fi
}

if ! command -v xcode-select >/dev/null 2>&1; then
    error "xcode-select was not found. Install Xcode 12.4 for macOS Catalina."
    exit 1
fi

XCODE_PATH=$(xcode-select -p 2>/dev/null) || {
    error "No Xcode developer directory is selected. Install Xcode 12.4, then run 'sudo xcode-select -s /Applications/Xcode.app/Contents/Developer'."
    exit 1
}

if [ ! -d "$XCODE_PATH" ]; then
    error "The selected developer directory does not exist: $XCODE_PATH"
    exit 1
fi

case "$XCODE_PATH" in
    */Contents/Developer) ;;
    *)
        error "The selected developer directory does not look like full Xcode: $XCODE_PATH"
        error "On Catalina, select full Xcode 12.4 with: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer"
        exit 1
        ;;
esac

if ! command -v xcrun >/dev/null 2>&1; then
    error "xcrun was not found. The selected Xcode developer tools appear incomplete: $XCODE_PATH"
    exit 1
fi

if ! xcrun -f xctest >/dev/null 2>&1; then
    error "xcrun cannot find xctest. The selected Xcode install may be incomplete or command line tools may be selected instead of full Xcode."
    error "Selected developer directory: $XCODE_PATH"
    error "On Catalina, install/open Xcode 12.4 and select it with: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer"
    exit 1
fi

if ! command -v swift >/dev/null 2>&1; then
    error "swift was not found in PATH. Install Xcode 12.4 or ensure Xcode's toolchain is selected."
    exit 1
fi

if [ ! -d "$PACKAGE_DIR" ]; then
    error "Swift package directory was not found: $PACKAGE_DIR"
    exit 1
fi

require_file "$PACKAGE_DIR/Package.swift"
require_file "$PACKAGE_DIR/Sources/CatalinaPerformance/main.swift"
require_executable_or_file "$SCRIPT_DIR/status_report.sh"
require_executable_or_file "$SCRIPT_DIR/performance_on.sh"
require_executable_or_file "$SCRIPT_DIR/performance_off.sh"
require_executable_or_file "$SCRIPT_DIR/emergency_restore.sh"

printf 'Using developer directory: %s\n' "$XCODE_PATH"
printf 'Building CatalinaPerformance GUI package: %s\n' "$PACKAGE_DIR"
cd "$PACKAGE_DIR" || exit 1
swift build

BUILT_EXECUTABLE="$PACKAGE_DIR/.build/debug/$APP_NAME"
if [ ! -f "$BUILT_EXECUTABLE" ]; then
    error "Built executable was not found: $BUILT_EXECUTABLE"
    exit 1
fi

printf 'Creating local app bundle: %s\n' "$APP_BUNDLE"
rm -rf "$APP_BUNDLE"
mkdir -p "$MACOS_DIR" || exit 1
cp "$BUILT_EXECUTABLE" "$GUI_EXECUTABLE" || exit 1
chmod 755 "$GUI_EXECUTABLE" || exit 1

cat > "$INFO_PLIST" <<'PLIST_EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleExecutable</key>
    <string>CatalinaPerformance</string>
    <key>CFBundleIdentifier</key>
    <string>local.CatalinaPerformance</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>CatalinaPerformance</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.15</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST_EOF

cat > "$BUNDLE_EXECUTABLE" <<EOF_LAUNCHER
#!/bin/sh
# Local development launcher generated by scripts/package_app.sh.
# Preserve an explicit CATALINA_PERFORMANCE_SCRIPTS_DIR when the caller sets it;
# otherwise point the GUI at the scripts directory in this checkout.

if [ -z "\${CATALINA_PERFORMANCE_SCRIPTS_DIR:-}" ]; then
    CATALINA_PERFORMANCE_SCRIPTS_DIR=\$(cat <<'SCRIPT_DIR_EOF'
$SCRIPT_DIR
SCRIPT_DIR_EOF
)
    export CATALINA_PERFORMANCE_SCRIPTS_DIR
fi

exec "\$(dirname "\$0")/${APP_NAME}-gui" "\$@"
EOF_LAUNCHER
chmod 755 "$BUNDLE_EXECUTABLE" || exit 1

printf 'Created %s\n' "$APP_BUNDLE"
printf 'Launch with: open %s\n' "$APP_BUNDLE"
printf 'This bundle is unsigned, not notarized, and intended only for local development. Keep this repository checkout available so the GUI can run the scripts.\n'
